# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_redo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedjob',
            name='date',
            field=models.CharField(max_length=255),
        ),
    ]
