# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20170124_0748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedjob',
            name='cached_job',
        ),
    ]
