# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 22:28
from __future__ import unicode_literals

from django.db import migrations

import csv

def load_keywords(apps, schema_editor):
	Keyword = apps.get_model("jobs", "Keyword")
	f = open('jobs/keywords.csv')
	csv_f = csv.reader(f)
	for i, row in enumerate(csv_f):
  		newky = Keyword(id=i,name=row[0],category=row[1])
  		newky.save
class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20170125_0356'),
    ]

    operations = [
    	 migrations.RunPython(load_keywords),
    ]
