# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='job_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='jobs',
            field=models.ManyToManyField(blank=True, to='jobs.SavedJob'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='yrs_exp',
            field=models.IntegerField(blank=True),
        ),
    ]
