# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20170123_0451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedjob',
            old_name='num_keywords',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='savedjob',
            name='snippet',
        ),
        migrations.RemoveField(
            model_name='savedjob',
            name='title',
        ),
        migrations.RemoveField(
            model_name='savedjob',
            name='url',
        ),
        migrations.AddField(
            model_name='savedjob',
            name='cached_job',
            field=models.OneToOneField(default='whatever', on_delete=django.db.models.deletion.CASCADE, to='jobs.CachedJob'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='yrs_exp',
            field=models.IntegerField(blank=True),
        ),
    ]
