branch-defaults:
  master:
    environment: qually-dev
global:
  application_name: qually
  branch: null
  default_ec2_keyname: qlw-eb
  default_platform: Python 2.7
  default_region: us-west-2
  profile: eb-cli
  repository: null
  sc: git
